### ISSUE TITLE
Can blink colors be configured the same way as blink durations

### ISSUE THREAD

**Issue by ctranstrum** [caksoylar/zmk-rgbled-widget#2]
This is a great widget!

I was hoping to be able to change the colors used for different parts of the widget. When the light blinks green or blue, I know immediately what it means, and when it blinks yellow I usually know what it means, since it's context sensitive, but when it blinks red, I don't immediately know whether I should charge my battery or I just lost my bluetooth connection.

I was wondering if it would be smart to change every color to something unique. There are seven statuses and seven colors available. For example, leave the battery as red, yellow, green, and layer change as cyan, but change connection to blue (connected), white (advertising), magenta (disconnected)?

Alternatively, is it easier to make the colors configurable? Then anyone can decide what color means what for themselves.

**Comment by caksoylar** [comment]
They currently are not, no. I'll look into converting them to Kconfig `choice`s, and see if it is feasible.

**Comment by caksoylar** [comment]
Thanks for the nice words, by the way! I agree that it might have been better to keep colors unique, but I also wanted to use the "intuitive" colors (at least according to me). At this point changing the defaults might not be a good idea, so I implemented configuration options in #4. It works OK with defaults but I want to test with different colors; let me know if you get a chance to test.

**Comment by ctranstrum** [comment]
Just tested, and can confirm that this approach works. Thanks so much for the quick turnaround on what was obviously a very low urgency request!

**Comment by caksoylar** [comment]
That's great, thanks! I'll merge then and if I broke anything hopefully I'll get reports :D
